import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Better Studio Log Viewer",
  icons: {
    icon: "/betterstudio-logo.png",
    shortcut: "/betterstudio-logo.png",
    apple: "/betterstudio-logo.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative min-h-screen overflow-x-hidden ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className="absolute inset-0 z-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: "url('/betterstudio-bg.png')" }}
        />
        <div className="relative z-10 min-h-screen">
          {children}
        </div>
        <footer className="bg-white/90 p-4 mt-6 rounded-lg">
          <p className="text-sm text-gray-600">© 2025 BetterStudio. All rights reserved.</p>
          <p className="text-sm text-gray-600">Made with ❤️ by Sarmad Hussain</p>
          <p className="text-sm text-gray-600">Version 1.0.0</p>
        </footer>

      </body>
    </html>
  );
}
